### ISSUE TITLE
About the details of M2 feature aggregation

### ISSUE THREAD

**Issue by weiyichang** [choyingw/M3-LRN#2]
Hi,

Thanks for sharing this nice work.

I have a simple question about the details of M2 feature aggregation in Fig S1:

It is about the mlp(64,64) after the landmark input (68,3) 

Is this mlp layer implemented with FC layer or 1D conv ?

The result of M2 feature aggregation looks good, and I would like to integrate this idea into our work.

So I would like to know the details about it, and I am looking forward to the code release

Thanks!!!

**Comment by choyingw** [comment]
Thank you for your interest. Those mlp layers share weights across the 68 points. You can either do a hard-coding way to init a (N_in, N_out) weight matrix and bias and apply them for all points, or used customized layer api for different framework. Stay tuned for our code release!
